import { productType } from "../types/Products";

export const products: productType[] = [
  {
    id: "1",
    name: "Shirt",
    image: [
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://w7.pngwing.com/pngs/895/199/png-transparent-spider-man-heroes-download-with-transparent-background-free-thumbnail.png",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
    ],
    price: 999.99,
    category: "clothing",
    ratings: 4.4,
    reviewsCount: 4,
    description: "This is a shirt",
    discountPercent: 57,
  },
  {
    id: "2",
    name: "shirt",
    image: [
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
    ],
    price: 1000,
    ratings: 0,
    reviewsCount: 0,
    category: "clothing",
    description: "akjvbkjans aj asva ascas asvasvaascascasc asv  asa asa   as ks njan jasjasoaias",
    // discountPercent: 20,
  },
  {
    id: "3",
    name: "Shirt",
    image: [
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://w7.pngwing.com/pngs/895/199/png-transparent-spider-man-heroes-download-with-transparent-background-free-thumbnail.png",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
    ],
    price: 999.99,
    category: "clothing",
    ratings: 4.4,
    reviewsCount: 4,
    description: "This is a shirt",
    discountPercent: 57,
  },
  {
    id: "4",
    name: "shirt",
    image: [
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
    ],
    price: 1000,
    ratings: 0,
    reviewsCount: 0,
    category: "clothing",
    description: "akjvbkjans aj asva ascas asvasvaascascasc asv  asa asa   as ks njan jasjasoaias",
    // discountPercent: 20,
  },
  {
    id: "5",
    name: "Shirt",
    image: [
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://w7.pngwing.com/pngs/895/199/png-transparent-spider-man-heroes-download-with-transparent-background-free-thumbnail.png",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
    ],
    price: 999.99,
    category: "clothing",
    ratings: 4.4,
    reviewsCount: 4,
    description: "This is a shirt",
    discountPercent: 57,
  },
  {
    id: "6",
    name: "shirt",
    image: [
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
    ],
    price: 1000,
    ratings: 0,
    reviewsCount: 0,
    category: "clothing",
    description: "akjvbkjans aj asva ascas asvasvaascascasc asv  asa asa   as ks njan jasjasoaias",
    // discountPercent: 20,
  },
  {
    id: "7",
    name: "Shirt",
    image: [
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://w7.pngwing.com/pngs/895/199/png-transparent-spider-man-heroes-download-with-transparent-background-free-thumbnail.png",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
    ],
    price: 999.99,
    category: "clothing",
    ratings: 4.4,
    reviewsCount: 4,
    description: "This is a shirt",
    discountPercent: 57,
  },
  {
    id: "91",
    name: "shirt",
    image: [
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
    ],
    price: 1000,
    ratings: 0,
    reviewsCount: 0,
    category: "clothing",
    description: "akjvbkjans aj asva ascas asvasvaascascasc asv  asa asa   as ks njan jasjasoaias",
    // discountPercent: 20,
  },
  {
    id: "43",
    name: "Shirt",
    image: [
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://w7.pngwing.com/pngs/895/199/png-transparent-spider-man-heroes-download-with-transparent-background-free-thumbnail.png",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
    ],
    price: 999.99,
    category: "clothing",
    ratings: 4.4,
    reviewsCount: 4,
    description: "This is a shirt",
    discountPercent: 57,
  },
  {
    id: "64",
    name: "shirt",
    image: [
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
    ],
    price: 1000,
    ratings: 0,
    reviewsCount: 0,
    category: "clothing",
    description: "akjvbkjans aj asva ascas asvasvaascascasc asv  asa asa   as ks njan jasjasoaias",
    // discountPercent: 20,
  },
  {
    id: "73",
    name: "Shirt",
    image: [
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://w7.pngwing.com/pngs/895/199/png-transparent-spider-man-heroes-download-with-transparent-background-free-thumbnail.png",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
    ],
    price: 999.99,
    category: "clothing",
    ratings: 4.4,
    reviewsCount: 4,
    description: "This is a shirt",
    discountPercent: 57,
  },
  {
    id: "20",
    name: "shirt",
    image: [
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
    ],
    price: 1000,
    ratings: 0,
    reviewsCount: 0,
    category: "clothing",
    description: "akjvbkjans aj asva ascas asvasvaascascasc asv  asa asa   as ks njan jasjasoaias",
    // discountPercent: 20,
  },
  {
    id: "9823",
    name: "Shirt",
    image: [
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://w7.pngwing.com/pngs/895/199/png-transparent-spider-man-heroes-download-with-transparent-background-free-thumbnail.png",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
    ],
    price: 999.99,
    category: "clothing",
    ratings: 4.4,
    reviewsCount: 4,
    description: "This is a shirt",
    discountPercent: 57,
  },
  {
    id: "243",
    name: "shirt",
    image: [
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
    ],
    price: 1000,
    ratings: 0,
    reviewsCount: 0,
    category: "clothing",
    description: "akjvbkjans aj asva ascas asvasvaascascasc asv  asa asa   as ks njan jasjasoaias",
    // discountPercent: 20,
  },
  {
    id: "65",
    name: "Shirt",
    image: [
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://w7.pngwing.com/pngs/895/199/png-transparent-spider-man-heroes-download-with-transparent-background-free-thumbnail.png",
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
      "https://wpkoi.com/demos3/narmada/wp-content/uploads/sites/11/2019/06/tshirt-2.jpg",
    ],
    price: 999.99,
    category: "clothing",
    ratings: 4.4,
    reviewsCount: 4,
    description: "This is a shirt",
    discountPercent: 57,
  },
  {
    id: "926",
    name: "shirt",
    image: [
      "https://img.freepik.com/free-psd/stylish-blue-plaid-shirt-men-isolated-transparent-background_191095-23044.jpg",
    ],
    price: 1000,
    ratings: 0,
    reviewsCount: 0,
    category: "clothing",
    description: "akjvbkjans aj asva ascas asvasvaascascasc asv  asa asa   as ks njan jasjasoaias",
    // discountPercent: 20,
  },
];
